### PR TITLE
Use var and null coalescing operator in a few places

### PR DESCRIPTION
**Pull request by Arcnor**
So as discussed in #16 , this is the first batch of changes I propose.

I actually have all the files changed in this way, but I realized later that your code style is different from C# standards, so I need to go and change a lot of things first (like `switch` indentations)

### CODE REVIEW

**Comment by JoeStrout** [comment]
Are you sure the null coalescing operator is available in Unity 5?  I thought this was a C# 6 feature (though I'm having trouble finding a definitive answer on that).

**Comment by Arcnor** [comment]
According to Rider they're available in language version C# 4.0 (which is what I mentioned in #16 I was going to target, with my reasoning about it, but it might of course be flawed).

**Comment by JoeStrout** [comment]
OK.  Just to be sure, I'll fire up Unity 5.5 and test it.  (I will probably be able to do that tomorrow; today I'm trying to push out a new version of Mini Micro!)

**Comment by Arcnor** [comment]
Awesome, good luck with that 🙂

**Comment by JoeStrout** [comment]
Tested and confirmed that `??` works fine in Unity 5.5/5.6.

**Comment by Arcnor** [comment]
Glad to hear 🙂. I'll open similar PRs for the rest of the files when I get the chance.

**Pull request merged**
